# Generated by Django 5.0.4 on 2024-04-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
